columns:
  numerical_columns:
    writing_score: int64
    reading_score: int64

  categorical_columns:
    gender: object
    race_ethnicity: object
    parental_level_of_education: object
    lunch: object
    test_preparation_course: object

  target_column: math_score